# Generated by Django 4.2.7 on 2023-12-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='task_datetime',
            new_name='assignment_datetime',
        ),
    ]
