# Generated by Django 4.2.7 on 2023-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_assignmentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentrecord',
            name='description',
            field=models.CharField(blank=True, max_length=750),
        ),
    ]
