# Generated by Django 4.2.7 on 2023-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_assignmentrecord_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentrecord',
            name='is_done',
        ),
        migrations.AddField(
            model_name='assignmentrecord',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('F', 'Failure'), ('I', 'Incomplete')], default='I', max_length=1),
        ),
    ]
