# Generated by Django 4.2.7 on 2023-12-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_description_assignmentrecord_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
