# Generated by Django 4.2.7 on 2024-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='religion',
            field=models.CharField(default='اسلام', max_length=20),
        ),
    ]
